// mac_llm_B.v
// Generated by: GPT-4o
module mac (
    input clk,
    input rst,
    input signed [7:0] a,
    input signed [7:0] b,
    output reg signed [31:0] out
);
    wire signed [15:0] product;
    assign product = a * b;
    always @(posedge clk) begin
        if (rst) begin
            out <= 32'sd0;
        end else begin
            out <= out + product;
        end
    end
endmodule
